# syntax=docker/dockerfile:1.6

# BASE IMAGE 
######################################################
FROM oven/bun:1.1.24-alpine AS base
WORKDIR /app

# DEPENDENCIES 
######################################################
FROM base AS dependencies
WORKDIR /app

COPY package.json ./
COPY bun.lockb ./
RUN bun install --frozen-lockfile

ENV NODE_ENV production

# BUILDER
######################################################
FROM dependencies AS builder
WORKDIR /app

COPY src ./src
COPY public ./public
COPY vite.config.ts ./
COPY index.html ./
RUN bun run build

EXPOSE 4173

CMD ["bun", "preview", "--host"]
